name: solana_mobile_wallet_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15
  solana: ^0.31.0
  solana_mobile_wallet: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mews_pedantic: ^0.26.0

flutter:
  uses-material-design: true
